"""A from-scratch transformer and neural network library built with NumPy."""

from rawformer.attention import (
    MultiHeadAttention,
    apply_rope,
    apply_rope_backward,
    build_rope_frequencies,
)
from rawformer.core import ForwardNotCalledError, Layer, ShapeMismatchError, SimpleLayer
from rawformer.layers import (
    Dropout,
    IdentityLayer,
    LayerNorm,
    LinearLayer,
    LoRALinear,
    PositionalEncoding,
    ReluLayer,
    RMSNorm,
    SigmoidLayer,
    SiLULayer,
    TanhLayer,
    TokenEmbedding,
    he_init,
    xavier_init,
    zeros_init,
)
from rawformer.losses import CrossEntropyLoss, Loss, MSELoss
from rawformer.models import MultiLayerNetwork
from rawformer.preprocessing import Preprocessor
from rawformer.tokenizers import BPETokenizer, WordPieceTokenizer
from rawformer.training import (
    DecoderOnlyModel,
    DPOTrainer,
    LMTrainer,
    MLMHead,
    Trainer,
    TrainerHyperparams,
    dpo_loss_and_grad,
    mask_tokens,
    sequence_log_probs,
)
from rawformer.transformer import (
    Decoder,
    DecoderBlock,
    Encoder,
    EncoderBlock,
    PositionWiseFeedForward,
    SwiGLUFeedForward,
    Transformer,
    causal_mask,
)

__all__ = [
    "BPETokenizer",
    "CrossEntropyLoss",
    "DPOTrainer",
    "Decoder",
    "DecoderBlock",
    "DecoderOnlyModel",
    "Dropout",
    "Encoder",
    "EncoderBlock",
    "ForwardNotCalledError",
    "IdentityLayer",
    "LMTrainer",
    "Layer",
    "LayerNorm",
    "LinearLayer",
    "LoRALinear",
    "Loss",
    "MLMHead",
    "MSELoss",
    "MultiHeadAttention",
    "MultiLayerNetwork",
    "PositionWiseFeedForward",
    "PositionalEncoding",
    "Preprocessor",
    "RMSNorm",
    "ReluLayer",
    "ShapeMismatchError",
    "SiLULayer",
    "SigmoidLayer",
    "SimpleLayer",
    "SwiGLUFeedForward",
    "TanhLayer",
    "TokenEmbedding",
    "Trainer",
    "TrainerHyperparams",
    "Transformer",
    "WordPieceTokenizer",
    "apply_rope",
    "apply_rope_backward",
    "build_rope_frequencies",
    "causal_mask",
    "dpo_loss_and_grad",
    "he_init",
    "mask_tokens",
    "sequence_log_probs",
    "xavier_init",
    "zeros_init",
]
